title: 추승우
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

gems: ['jekyll-multiple-languages']
languages: ['ko', 'en']
language_default: 'ko'
fill_default_content: true


url: http://sungwoo.me
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: kswchoo
   twitter: kswchoo
   facebook: kswchoo
   email: choo@sungwoo.me

google_analytics: ""



